### PR TITLE
Eula

### PR DESCRIPTION
**Pull request by Ivylyu**
add an End User License Agreement on Footer

### CODE REVIEW

**Comment by mwpeng** [comment]
@Ivylyu  would you please set the reviewers after creating PR,  reviewers will be notified if so.

**Comment by mwpeng** [comment]
@whimet the build of buddy is red, but follow the details link the build can not be found.     Would you please confirm that we are good to merge this .

**Comment by mwpeng** [comment]
@whimet @MrCoder please submit your review for this.

**Comment by Ivylyu** [comment]
all good

**Pull request merged**
